from elevator.models import Build

b = Build(4)
print(f"building has {b.floors} floors")
print("I was built")
print("yes i was")
print("yes i was")
print("yes i was")
print("yes i was")
print("did i just appear??")
print("now?")
print("now?")
print("now?")
print("now?")
print("now?")
