from elevator.models import Build

b = Build(4)
print("did cron bring this???")
print("did cron bring this???")
print("did cron bring this???")
print("did cron bring this???")
print("did cron bring this???")
print("cron bring this???")
print("cron bring this???")
print("cron bring this???")
print("cron bring this???")
print("cron bring this???")
print("did cron bring this???")
print("elevate")
print("elevate")
print("elevate")
